name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec ./1/a/1/spec.cr
          # ./1/a/2/spec.cr
          # ./1/a/3/spec.cr
          # ./1/a/4/spec.cr
          # ./1/a/5/spec.cr
          # ./1/a/6/spec.cr
          # ./1/a/7/spec.cr
          # ./1/a/14/spec.cr
          # ./1/a/16/spec.cr
          # ./1/a/22/spec.cr
